### PR TITLE
Bug 1912237: Rebase to v2.2.0 for OCP 4.7

### PR DESCRIPTION
**Pull request by jsafrane**
Diff to upstream v2.2.0:
https://github.com/kubernetes-csi/livenessprobe/compare/v2.2.0...jsafrane:rebase-v2.2.0

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
This requires new golang in CI jobs: https://github.com/openshift/release/pull/14560

**Comment by bertinatto** [comment]
Probably in another PR, but do we need to update the golang version here as well?

https://github.com/kubernetes-csi/livenessprobe/compare/v2.2.0...jsafrane:rebase-v2.2.0#diff-f20a7cf8ba7e8b20f3bd1963e18191e6ba4474bb0bf92bdd745bb62841e4a6c3R1

**Pull request merged**
